import type { Metadata } from 'next'
import TopBar from '@/components/TopBar'
import SideBar from '@/components/SideBar'
import { Fellix } from '@/styles/fonts'
import '@/styles/globals.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="es" suppressHydrationWarning>
            <body className={Fellix.className}>
                <TopBar />
                <SideBar />
                <main
                    className={
                        'h-full flex ml-14 pt-20 p-6 min-h-screen md:ml-64 bg-neutral-100 dark:bg-neutral-900 transition-all duration-300'
                    }
                >
                    {children}
                </main>
            </body>
        </html>
    )
}
