import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import TopBar from '@/components/TopBar'
import SideBar from '@/components/SideBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="es">
            <body className={inter.className}>
                <TopBar />
                <SideBar />
                <div
                    id="detail"
                    className={
                        'h-full flex ml-14 pt-20 p-6 min-h-screen md:ml-64 bg-neutral-100 dark:bg-neutral-900 transition-all duration-300'
                    }
                >
                    <main>{children}</main>
                </div>
            </body>
        </html>
    )
}
